apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-expense 
provisioner: efs.csi.aws.com
parameters: 
  provisioingMode: efs-ap
  fileSytemId: fs-0c32c2309f2eb5c1e
  directoryPerms: "700"
  basePath: "/expense"